name: Node.js CI

permissions:
  contents: read

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: volta-cli/action@5c175f92dea6f48441c436471e6479dbc192e194
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test
      - uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
